export const kelas = [
  {
    img: "/images/FO.png",
    title: "The Founder",
    desc: "Membangun startup dari awal hingga menjadi MVP dan melakukan pitching di depan calon investor",
    level: "Semua Level",
    bulan: "6 Bulan intensif",
    Tanggal: "dari 30 Agustus",
    online: "Online",
  },
  {
    img: "/images/DS.png",
    title: "Data Science",
    desc: "Menerapkan statistik terapan untuk pengembangan produk yang berkelanjutan",
    level: "Semua Level",
    bulan: "6 Bulan intensif",
    Tanggal: "dari 31 Agustus",
    online: "Online",
  },

  {
    img: "/images/UIUX.png",
    title: "UI/UX Design",
    desc: "Membuat desain dengan menerapkan pendekatan yang berpusat pada pengalaman pengguna",
    level: "Menengah",
    bulan: "6 Bulan",
    Tanggal: "7 Juli - 1 Desember 2022",
    online: "Offline",
  },
  {
    img: "/images/DS.png",
    title: "Artificial Intelligence",
    desc: "Mempelajari dan merancang penyelesaian permasalahan dengan menerapkan pendekatan dan model AI",
    level: "Menengah",
    bulan: "6 Bulan",
    Tanggal: "7 Juli - 1 Desember 2022",
    online: "Offline",
  },
  {
    img: "/images/FO.png",
    title: "Backend Engineer",
    desc: "Merancang, memrogram, dan mengimplementasikan sisi backend dari sebuah website/web application",
    level: "Semua Level",
    bulan: "9 Bulan Intensif",
    Tanggal: "dari 3 September",
    online: "Online",
  },
];
